---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: magnognaclassic
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 43 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
        
  - type: dnf
    repos:
      copr:
        - ublue-os/packages
        - kylegospo/webapp-manager
        
  - type: dnf
    install:
      packages:   
      #gnome
        - gnome-shell-extension-unite
        - gnome-shell-extension-dash-to-panel
        - gnome-shell-extension-just-perfection 
        - yaru-theme
        - gnome-shell-extension-appindicator
        - gnome-shell-extension-caffeine 
        - gnome-tweaks
        - dconf-editor
        - gnome-calculator
        - gnome-calendar
        - papers
        - loupe
        - adw-gtk3-theme
      #utils
        - webapp-manager
        - gnome-classic-session
        - bazaar
        - lshw
        - cockpit
        - cockpit-podman
      #build
        - make
        - gawk
      #appimages
        - fuse
        - fuse-libs
      #VM
        - spice-vdagent

    remove:
      packages:
        - gnome-software

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - com.github.tchx84.Flatseal

  - type: systemd
    system:
      enabled:
      - cockpit.socket
  
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
